disallowed-methods = [
    { path = "std::slice::from_raw_parts", reason = "see null_safe_slice" }
]
disallowed-macros = [
    { path = "dbg!" }
]
allow-mixed-uninlined-format-args = false
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
pass-by-value-size-limit = 16
# avoid-breaking-exported-api = false # TODO: Enable this in a follow-on PR.
