name: 'Install tshark'
description: 'Install a recent build of tshark.'

runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux' && runner.environment == 'github-hosted'
      shell: bash
      run: |
        sudo add-apt-repository ppa:wireshark-dev/stable
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends tshark firefox

    - if: runner.os == 'MacOS' && runner.environment == 'github-hosted'
      shell: bash
      run: |
        brew install tshark firefox

    - if: runner.os == 'Windows' && runner.environment == 'github-hosted'
      shell: bash
      run: echo "Windows is unsupported"

    - shell: bash
      if: runner.os != 'Windows' && runner.environment == 'github-hosted'
      run: |
        tshark --version
        firefox --version
