name: 'Install tshark'
description: 'Install a recent build of tshark.'

runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux' && runner.environment == 'github-hosted'
      shell: bash
      run: |
        sudo add-apt-repository ppa:wireshark-dev/stable
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends wireshark firefox

    - if: runner.os == 'MacOS' && runner.environment == 'github-hosted'
      shell: bash
      run: |
        brew install wireshark firefox

    - if: runner.os == 'Windows' && runner.environment == 'github-hosted'
      shell: bash
      run: |
        choco install -y wireshark firefox

    - shell: bash
      run: |
        wireshark --version
        firefox --version
